apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idt-mqtt
spec:
  project: industrial-digital-twin
  source:
    repoURL: https://github.com/idtMicroservice/GitOps.git
    targetRevision: main
    path: base/mqtt
  destination:
    server: https://kubernetes.default.svc
    namespace: idt-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true