apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: idt-demo
resources:
  - namespace.yaml
  - ../../base
  - ../../base/simulator
images:
  - name: idt/frontend
    newName: docker.io/manojkrishnappa/idt-frontend
    newTag: '47b8ebc'
  - name: idt/backend
    newName: docker.io/manojkrishnappa/idt-backend
    newTag: '52a8202'
  - name: idt/auth-db
    newName: docker.io/manojkrishnappa/idt-auth-db
    newTag: '279fe55'
  - name: idt/simulator
    newName: ghcr.io/replace-me/idt-simulator
    newTag: replace-with-git-sha
patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DEMO_SIMULATION_ENABLED
          value: "true"