apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: industrial-digital-twin
spec:
  sourceRepos:
    - https://github.com/idtMicroservice/GitOps.git
  destinations:
    - namespace: idt-demo
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"