apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: manojkrishnappa/idt-simulator
    newName: docker.io/manojkrishnappa/idt-simulator
    newTag: "52a8202"
